// Package openapi строит спецификацию OpenAPI из реестра маршрутов.
package openapi

import (
	"fmt"
	"strings"

	"github.com/akozadaev/guardian/internal/api"
	"github.com/swaggest/openapi-go"
	"github.com/swaggest/openapi-go/openapi3"
)

const securityName = "bearerAuth"

type operationAccessor interface {
	Operation() *openapi3.Operation
}

// Generate возвращает спецификацию OpenAPI 3.0.3 в YAML.
func Generate() ([]byte, error) {
	reflector := openapi3.NewReflector()
	spec := reflector.SpecEns()
	spec.SetTitle("Guardian Proxy Admin API")
	spec.SetVersion("1.0.0")
	spec.SetDescription("Административный API высокопроизводительного фильтрующего прокси-сервера Guardian.")
	spec.WithServers(openapi3.Server{URL: "/"})
	spec.SetHTTPBearerTokenSecurity(securityName, "JWT", "JWT административного API")

	for _, route := range api.AdminRoutes() {
		operation, err := reflector.NewOperationContext(route.Method, route.Path)
		if err != nil {
			return nil, fmt.Errorf("create operation %s %s: %w", route.Method, route.Path, err)
		}
		operation.SetSummary(route.Summary)
		operation.SetID(operationID(route.Method, route.Path))
		if route.Description != "" {
			operation.SetDescription(route.Description)
		}
		if route.Security {
			operation.AddSecurity(securityName)
			addResponse(operation, 401, "Требуется аутентификация", api.ErrorResponse{})
			addResponse(operation, 403, "Недостаточно прав", api.ErrorResponse{})
		}

		if route.RequestBody != nil {
			operation.AddReqStructure(route.RequestBody, func(unit *openapi.ContentUnit) {
				unit.ContentType = "application/json"
				unit.Customize = func(content openapi.ContentOrReference) {
					if body, ok := content.(*openapi3.RequestBodyOrRef); ok {
						body.RequestBodyEns().WithRequired(true)
					}
				}
			})
		}

		accessor, ok := operation.(operationAccessor)
		if !ok {
			return nil, fmt.Errorf("operation %s %s does not expose OpenAPI operation", route.Method, route.Path)
		}
		for _, parameter := range route.Parameters {
			schema := (&openapi3.Schema{}).WithType(openapi3.SchemaType(parameter.Type))
			if parameter.Format != "" {
				schema.WithFormat(parameter.Format)
			}
			accessor.Operation().Parameters = append(accessor.Operation().Parameters, openapi3.ParameterOrRef{
				Parameter: &openapi3.Parameter{
					Name:        parameter.Name,
					In:          openapi3.ParameterIn(parameter.In),
					Description: optionalString(parameter.Description),
					Required:    optionalBool(parameter.Required),
					Schema:      &openapi3.SchemaOrRef{Schema: schema},
				},
			})
		}

		for _, response := range route.Responses {
			addResponse(operation, response.Status, response.Description, response.Body)
		}
		if err := reflector.AddOperation(operation); err != nil {
			return nil, fmt.Errorf("add operation %s %s: %w", route.Method, route.Path, err)
		}
	}

	data, err := spec.MarshalYAML()
	if err != nil {
		return nil, fmt.Errorf("marshal OpenAPI: %w", err)
	}
	return append([]byte("# Code generated by `make openapi`; DO NOT EDIT.\n"), data...), nil
}

func addResponse(operation openapi.OperationContext, status int, description string, body any) {
	operation.AddRespStructure(body, func(unit *openapi.ContentUnit) {
		unit.HTTPStatus = status
		unit.Description = description
		if body != nil {
			unit.ContentType = "application/json"
		}
	})
}

func operationID(method, path string) string {
	value := strings.ToLower(method) + "_" + strings.Trim(path, "/")
	return strings.NewReplacer("/", "_", "{", "", "}", "", "-", "_").Replace(value)
}

func optionalString(value string) *string {
	if value == "" {
		return nil
	}
	return &value
}

func optionalBool(value bool) *bool {
	if !value {
		return nil
	}
	return &value
}
